<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OT</name>
   <tag></tag>
   <elementGuidId>debb755f-741b-47df-94d8-e439c06ba38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top-panel-avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-panel-avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47991439-6b30-4cfc-86bb-401a5280ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-panel-avatar</value>
      <webElementGuid>1996d5f9-7c35-420f-8c4c-85907db9e975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-initials</value>
      <webElementGuid>601612f5-ebfb-4001-b0c9-767de0ed7676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OT </value>
      <webElementGuid>a7b6c86a-7895-489f-9196-332a3600e48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-panel-avatar&quot;)</value>
      <webElementGuid>5ec56390-85c0-436a-95f6-152d90531539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='top-panel-avatar']</value>
      <webElementGuid>3335865c-cacc-422c-9ed9-fcf995c97e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTSjusn'])[1]/preceding::div[2]</value>
      <webElementGuid>bbe88874-c4c2-4956-bb22-6bf114011bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OT']/parent::*</value>
      <webElementGuid>22e0669b-03f5-4a86-8d40-0cf5a62a88c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>7dd94b61-ece1-4c1b-ad68-635acdd4de5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-panel-avatar' and (text() = ' OT ' or . = ' OT ')]</value>
      <webElementGuid>55af3386-a7be-408d-9a82-3f865b35275c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
