<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_logoutLog Out</name>
   <tag></tag>
   <elementGuidId>355c4e7b-86e2-4050-a95a-35e2360ba419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-panel-avatar']/app-dropdown-menu/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93c51b5c-0d98-4dc6-bc64-5283f35a2f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-card ng-star-inserted</value>
      <webElementGuid>6a8c7467-aeb7-46ce-b5f0-e4122b588b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>74dd0c71-6a10-4a3a-801a-c0bd4fa8278c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logoutLog Out</value>
      <webElementGuid>e5dff710-000d-4639-8a90-757a5118181b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-panel-avatar&quot;)/app-dropdown-menu[1]/div[@class=&quot;dropdown-menu ng-star-inserted&quot;]/div[@class=&quot;selection-card ng-star-inserted&quot;]</value>
      <webElementGuid>14142a31-eeab-476f-924d-40b32147037c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-panel-avatar']/app-dropdown-menu/div/div[2]</value>
      <webElementGuid>66789082-76b9-4960-a0f3-42670075f2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PTSjusn'])[1]/preceding::div[2]</value>
      <webElementGuid>8cafae22-4e80-48ab-9f2d-a50228a1adb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dropdown-menu/div/div[2]</value>
      <webElementGuid>dc111ddb-a541-4657-bb58-dc5d7ee122ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'logoutLog Out' or . = 'logoutLog Out')]</value>
      <webElementGuid>0e17fa27-7c13-46fe-8943-6e8dc9177de7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
