<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sharedInput</name>
   <tag></tag>
   <elementGuidId>5dd68685-af60-4c00-9ca4-6d603e9f636a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-label-input[name=&quot;password&quot;] > div.label-input-container > input.sharedInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3a068a4-574c-4824-ac82-9373e4caf9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sharedInput</value>
      <webElementGuid>b51ad8b7-f612-4cbb-bfb7-d9914d38d367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d1533ce3-cd11-4699-80af-2dcab6622eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Password</value>
      <webElementGuid>3ea0b2ac-b507-4322-99ab-cc167e47a48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f6503018-89c8-48d6-ae32-dec0c2c8e05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>4ac738dd-b4e8-4ac4-81c4-f88d5bc12b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[1]/div[@class=&quot;login-container&quot;]/div[@class=&quot;center-wrapper&quot;]/app-login[1]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;input-fields-error-wrapper&quot;]/div[@class=&quot;input-fields&quot;]/app-label-input[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;label-input-container&quot;]/input[@class=&quot;sharedInput&quot;]</value>
      <webElementGuid>04464c9e-1d7a-4456-b95d-cfda671d1583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>a2815a05-6ff3-44e3-8619-7e10e54a6e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-label-input[2]/div/input</value>
      <webElementGuid>9a2d6ad8-ffa1-44fa-a81d-9a8febad67bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Your Password']</value>
      <webElementGuid>319facbc-894f-469e-a6c2-a98b54d7e8da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
