<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finalize</name>
   <tag></tag>
   <elementGuidId>51f80c67-4f92-48ba-85a7-1344a1051eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.primary-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-advanced-features >> internal:role=button[name=&quot;Finalize&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23812e34-bba0-4b27-9266-0f83cbac3235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary-button</value>
      <webElementGuid>3038eb98-d207-4ac5-8f82-e6431372a188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>cd74567e-d40e-4215-833f-8ff3e8ec85eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2018889-3d1e-43ea-92e8-8ef26d601c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Finalize
</value>
      <webElementGuid>afd85d52-0006-480e-8281-6454e01790c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content&quot;]/app-video-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex-column&quot;]/div[@class=&quot;wrapper ng-star-inserted&quot;]/div[@class=&quot;video-and-notes-wrapper&quot;]/div[@class=&quot;advanced-features-wrapper ng-star-inserted&quot;]/app-advanced-features[1]/div[@class=&quot;advanced-features-container&quot;]/div[@class=&quot;advanced-feature&quot;]/div[@class=&quot;modal ng-star-inserted&quot;]/div[@class=&quot;advanced-features-modal-buttons&quot;]/app-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;button primary-button&quot;]</value>
      <webElementGuid>80d82625-e214-4769-a7b2-21bcbf192106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>f3bfa3a5-5ef7-4900-bfb3-f0996396a8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Features Unavailable'])[1]/following::button[1]</value>
      <webElementGuid>e6a51e6a-86ab-4ad6-871f-b66aa6a41734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedure Breakdown (BETA)'])[1]/following::button[1]</value>
      <webElementGuid>afd0d505-73dc-468e-a58f-5efc351d7ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalize']/parent::*</value>
      <webElementGuid>443831b4-d97f-4c40-a4fb-c46363e66c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/app-button/button</value>
      <webElementGuid>950c7d2b-1654-44a9-bf1f-316f1999119b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Finalize
' or . = ' Finalize
')]</value>
      <webElementGuid>5b349a18-0ab2-4a3c-856a-96000a6773d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
