<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_arrow_rightfolder_copy My procedures</name>
   <tag></tag>
   <elementGuidId>13886aa2-756d-44c1-92f1-8160b407a398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ee'])[1]/following::div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.drop-down-menu-item.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;arrow_rightfolder_copy My procedures&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92734d1b-0bcb-41b1-b60b-6f3e378716a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>3675a4ae-f6f3-4634-ac11-f9f7fdb54ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drop-down-menu-item active</value>
      <webElementGuid>e40f3f76-75b0-48e2-bf02-33cb44c56b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77ca46cd-4f82-4dfd-9eff-20dbc5256035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>4228b6c9-5c6f-4935-a90e-a1e7fccbc797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/my-procedures</value>
      <webElementGuid>f6e28676-93cf-4b1d-b774-6d6502552956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_rightfolder_copy My procedures </value>
      <webElementGuid>73db04a1-f1b6-4a9c-bcb3-19210005d1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[@class=&quot;content-wrapper&quot;]/app-left-panel[1]/div[@class=&quot;menu mobile-view&quot;]/app-side-menu[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;drop-down-menu-item active&quot;]</value>
      <webElementGuid>b11fb1f6-49ed-44e4-9c47-699e30360074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ee'])[1]/following::div[5]</value>
      <webElementGuid>3da0f3f8-04df-497f-b65b-ebb32fe92185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test123'])[1]/preceding::div[1]</value>
      <webElementGuid>bd3795d7-e0f7-4528-a134-7c9a81250785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing1'])[1]/preceding::div[3]</value>
      <webElementGuid>9810d246-9f9c-4112-b798-865c9e936b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My procedures']/parent::*</value>
      <webElementGuid>e2018797-52b3-494d-9477-5c173dfc97af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-side-menu/div/div/div</value>
      <webElementGuid>95f6fb41-3d99-4695-9512-80e2b5ff08b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'arrow_rightfolder_copy My procedures ' or . = 'arrow_rightfolder_copy My procedures ')]</value>
      <webElementGuid>d8eb400d-4ddf-4e43-a58f-f501947d5247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
