<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tr</name>
   <tag></tag>
   <elementGuidId>33d999fd-ba0e-4000-8238-06cd7c3fe2d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-panel-avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#top-panel-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tr&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c10c6f77-8521-4dbe-adf4-389ea454ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-panel-avatar</value>
      <webElementGuid>7307d128-1d54-4d83-9afd-243b062d3fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-initials</value>
      <webElementGuid>eee4d28b-230c-4d67-808e-816eab2dcea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tr </value>
      <webElementGuid>eb428b4d-b240-4184-96a0-eba3c033accb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-panel-avatar&quot;)</value>
      <webElementGuid>2793d8ac-f991-41a7-883d-41aaa45427b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='top-panel-avatar']</value>
      <webElementGuid>75ca61a2-dab0-4fc3-a284-ca75c6952613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='procedure'])[1]/preceding::div[3]</value>
      <webElementGuid>c2397480-9bff-4462-a05b-7a25eba4dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tr']/parent::*</value>
      <webElementGuid>88daeb35-aac0-4514-81e8-f00bd7465297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>71627212-c65e-4165-b86a-97cc0bf7446c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-panel-avatar' and (text() = ' Tr ' or . = ' Tr ')]</value>
      <webElementGuid>d5aa3888-f37e-4978-b3b2-ae92106ea348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
