<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ee</name>
   <tag></tag>
   <elementGuidId>d2243ed1-aac7-4e31-8889-182686aca380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-panel-avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#top-panel-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ee&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98621d2d-7ad2-4e75-8005-a6ae81111802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-panel-avatar</value>
      <webElementGuid>610ed639-fbba-4582-b0af-296f2e9c7406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-initials</value>
      <webElementGuid>367dbf31-0ec3-410e-845f-d18dc75c94c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ee </value>
      <webElementGuid>d8766013-546e-45c1-a118-f117f895f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-panel-avatar&quot;)</value>
      <webElementGuid>8ef83f24-76ca-4d8e-8b12-1bdf36fef4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='top-panel-avatar']</value>
      <webElementGuid>5bc25c0b-db21-40b6-8cf2-4a3da0709f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test123'])[1]/preceding::div[2]</value>
      <webElementGuid>61fdb312-c21e-4a0f-ad5c-69d8f8c15a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ee']/parent::*</value>
      <webElementGuid>1711f850-1400-4856-9bbe-4880385ebaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>beea419c-6802-4f82-afda-97b68e8c4ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-panel-avatar' and (text() = ' ee ' or . = ' ee ')]</value>
      <webElementGuid>fbb46220-dd6a-46c0-8712-59887ae1bd53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
