<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_arrow_drop_down</name>
   <tag></tag>
   <elementGuidId>5bef88b1-2031-4937-acd7-63930b704bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[3]/following::mat-icon[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.dropdown-icon-closed.material-icons.mat-ligature-font.mat-icon-no-color.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:text=&quot;arrow_drop_down&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>638c0237-170d-42d4-ab9b-db9f11a59281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>417ba59f-5b03-4389-8d5e-55276da7ddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate dropdown-icon-closed material-icons mat-ligature-font mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>ed9b0d5c-75c7-4220-8d83-3956b7e04186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63af031d-3ae9-4ef7-a6aa-1c54db652433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>44555b50-1324-48dc-b802-7dd73efcda15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> arrow_drop_down </value>
      <webElementGuid>07bc71d3-4f9e-458d-8dc7-b6ee8c8d37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content&quot;]/app-my-procedures[@class=&quot;ng-tns-c2724626422-0 ng-star-inserted&quot;]/app-popup-modal[@class=&quot;ng-tns-c2724626422-0&quot;]/div[@class=&quot;modal-overlay ng-star-inserted&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-content&quot;]/app-create-procedure[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;create-procedure-container&quot;]/form[@class=&quot;create-procedure-body ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;all-platform-access-container ng-star-inserted&quot;]/div[@class=&quot;all-platform-access-info&quot;]/div[@class=&quot;all-platform-access-text&quot;]/div[@class=&quot;all-platform-access-text-header&quot;]/div[@class=&quot;icon-button-container&quot;]/div[@class=&quot;icon-button&quot;]/mat-icon[@class=&quot;mat-icon notranslate dropdown-icon-closed material-icons mat-ligature-font mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>3ab718f4-cecc-49bb-a6f3-6fddb93cc0e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[3]/following::mat-icon[1]</value>
      <webElementGuid>6d044751-4aca-4fab-9e7b-d4b79ccd44a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/following::mat-icon[2]</value>
      <webElementGuid>426c43b1-3b7f-4390-a13d-22de2bd444a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only people you shared with can view the procedure.'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>85cb20b9-584c-4e96-90e5-89f846f6047d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>b6375886-72b4-44fa-b336-1bf319f2e720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/mat-icon</value>
      <webElementGuid>d482ba01-ae54-4845-8458-507dfed8c674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' arrow_drop_down ' or . = ' arrow_drop_down ')]</value>
      <webElementGuid>4a729941-34b6-458f-a67b-6e9227e0601a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
