<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_meghatest</name>
   <tag></tag>
   <elementGuidId>88a2992e-d215-49db-881a-40879644fa66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ee'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.procedure-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;meghatest&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b07c61d3-942c-4219-8c96-b5880d2ec909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>procedure-name</value>
      <webElementGuid>a5974c9d-71c7-411b-b314-3d479dadc9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>meghatest</value>
      <webElementGuid>cc1a8dd3-687a-4fe9-bbc4-092144359555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>meghatest</value>
      <webElementGuid>f8603559-135e-4a5f-80c0-1e5b2d9182d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[@class=&quot;content-wrapper&quot;]/app-left-panel[1]/div[@class=&quot;menu mobile-view&quot;]/app-side-menu[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;procedures-list remove-on-mobile&quot;]/div[@class=&quot;icon-and-proc-name active-procedure ng-star-inserted&quot;]/span[@class=&quot;procedure-name&quot;]</value>
      <webElementGuid>55a03ace-4e50-4cba-8e6c-aac726dfe6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ee'])[1]/following::span[1]</value>
      <webElementGuid>4beb7776-b9fe-43ab-ab14-f2112fa883ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test123'])[1]/preceding::span[1]</value>
      <webElementGuid>6ba6fa37-abdd-4f7e-8665-9c5ef8c61fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing1'])[1]/preceding::span[3]</value>
      <webElementGuid>f7ac9bb8-ea7a-47e5-ad55-866ae8ea96d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='meghatest']/parent::*</value>
      <webElementGuid>c7e9e61c-c068-4265-b167-b1ae1e3ef22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ebc47b26-8079-4f9f-950d-387606a0191c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'meghatest' and (text() = 'meghatest' or . = 'meghatest')]</value>
      <webElementGuid>db81369b-ddf1-4418-bbbb-3c9d23f490bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
