<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(Optional)_procedureDescription</name>
   <tag></tag>
   <elementGuidId>04ad6a01-ecbb-4aee-b082-6244b620408c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='procedureDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;procedureDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;procedureDescription&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>46c9bb2e-ea74-4543-8bd8-224ece55cd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedureDescription</value>
      <webElementGuid>f17f6aef-3c18-46c2-bfd9-6504549ff3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1a0de82-9e23-4ce4-a588-0069b6e78cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>a1aae892-0999-4f44-ac6a-6f79e2365b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>procedure-description-text ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>8f12d76e-e812-4f8b-902a-7f882e4453db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3871dc04-14ca-44c4-bba3-11a7c1a75489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>procedureDescription</value>
      <webElementGuid>5f26136f-1b4a-4719-b991-834f3befce32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>41b3adf4-c159-44e5-929f-af3c86a4f910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[1]/app-layout[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content&quot;]/app-my-procedures[@class=&quot;ng-tns-c2724626422-0 ng-star-inserted&quot;]/app-popup-modal[@class=&quot;ng-tns-c2724626422-0&quot;]/div[@class=&quot;modal-overlay ng-star-inserted&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-content&quot;]/app-create-procedure[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;create-procedure-container&quot;]/form[@class=&quot;create-procedure-body ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;procedure-description&quot;]/div[@class=&quot;procedure-description-input-container&quot;]/textarea[@class=&quot;procedure-description-text ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>7479ad38-f4f8-4085-afa8-bfdd10a6182c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='procedureDescription']</value>
      <webElementGuid>92aa5a2e-9687-4e43-aa9a-7ea5c8b8870c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b163251d-f438-4112-83c9-3cfdc7efabd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'procedureDescription']</value>
      <webElementGuid>3a3d2659-8780-456e-ab6d-a8c48acbd091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
